version: '3'
services:
  nginx:
    image: nginx
    network_mode: host
    volumes:
    - "./letsencrypt:/etc/letsencrypt:ro"
    - "http_challenge:/var/www/.well-known:ro"
    - "./scripts:/scripts"
    env_file:
    - domains.env # copy domains.example.env to domains.env

    command: /bin/bash -c "/scripts/generate-config.sh && exec nginx -g 'daemon off;'"

  certbot:
    image: certbot/certbot
    volumes:
    - "./letsencrypt:/etc/letsencrypt"
    - "http_challenge:/var/www/.well-known"
    - "./scripts:/scripts"

    env_file:
    - domains.env # copy domains.example.env to domains.env

    entrypoint: sh -c
    command: certbot renew

volumes:
  http_challenge: ~