version: '3'
services:
  nginx:
    image: nginx
    network_mode: host
    volumes:
    - "./conf.d:/etc/nginx/conf.d:ro"
    - "./letsencrypt:/etc/letsencrypt"
    - "http_challenge:/var/www/.well-known"

  certbot:
    image: certbot/certbot
    volumes:
    - "./letsencrypt:/etc/letsencrypt"
    - "./conf.d:/etc/nginx/conf.d"
    - "http_challenge:/var/www/.well-known"
    command: ["renew"]

volumes:
  http_challenge: ~