version: '3'
services:
  nginx:
    image: nginx
    network_mode: host
    volumes:
    - "./letsencrypt:/etc/letsencrypt:ro"
    - "http_challenge:/var/www/.well-known:ro"
    - "./scripts:/scripts"
    - "./config:/config"

    command: /bin/bash -c "/scripts/generate-config.sh && exec nginx -g 'daemon off;'"

  certbot:
    image: certbot/certbot
    volumes:
    - "./letsencrypt:/etc/letsencrypt"
    - "http_challenge:/var/www/.well-known"
    - "./scripts:/scripts"
    - "./config:/config"

    entrypoint: sh -c
    command: certbot renew

volumes:
  http_challenge: ~
